const { serialize } = require('../../../services/serializers')

exports.PERMITED_COLLECTION_PARAMS = [
  'id',
  'propertyId',
  'propertyUnitTypeId',
  'propertyUnitTypeUnitId',
  'propertyName',
  'propertyUnitTypeName',
  'propertyUnitTypeUnitName',
  'propertyUnitTypeUnitDeletedAt',
  'dateArrival',
  'dateDeparture',
  'checkinAt',
  'checkoutAt',
  'totalNights',
  'totalGuests',
  'guestsInfants',
  'guestName',
  'multipleUnitTypes',
  'status',
  'amountTotal',
  'currency',
  'createdAt',
  'updatedAt',
  'deletedAt',
]

exports.PERMITED_ITEM_PARAMS = [
  'id',
  'propertyId',
  'propertyUnitTypeId',
  'propertyUnitTypeUnitId',
  'propertyName',
  'propertyUnitTypeName',
  'propertyUnitTypeUnitName',
  'propertyUnitTypeUnitDeletedAt',
  'multipleUnitTypes',
  'dateArrival',
  'dateDeparture',
  'dateConfirmed',
  'dateCanceled',
  'optionExpirationDate',
  'checkinAt',
  'checkoutAt',
  'guestsAdults',
  'guestsInfants',
  'guestsChildren',
  'guestsTeens',
  'guestsInfants',
  'status',
  'canceledBy',
  'channelName',
  'channelCommission',
  'amountDiscount',
  'amountAccommodationDue',
  'amountSecureDeposited',
  'amountTotalPaid',
  'amountTotalTax',
  'amountTotal',
  'currency',
  'promoCode',
  'source',
  'notes',
  'guest',
  'createdAt',
  'updatedAt',
]

exports.serialize = serialize
