const { seed } = require('../../src/services/seeder')
const { TABLE_NAME, CATEGORIES } = require('../../src/models/v1/dict-amenities/constants')

const DICTIONARY_AMENITIES = {
  [CATEGORIES.ACCESSIBILITY]: [
    { name: 'elevatorInBuilding', channexId: '91387c6b-ac21-46f1-ab1b-1147550d8fe1', type: null },
    { name: 'suitableForElderlyOrInfirm', channexId: '', type: null },
    { name: 'suitableForEvents', channexId: '', type: null },
    { name: 'unsuitableForElderlyOrInfirm', channexId: '', type: null },
    { name: 'wheelchairAccessible', channexId: '1f39462f-0cdd-489f-854a-db06485271c6', type: null },
    { name: 'wheelchairInaccessible', channexId: '', type: null },
  ],
  [CATEGORIES.BATHROOM_AND_LAUNDRY]: [
    { name: 'bathroomAndLaundry', channexId: '', type: null },
    { name: 'bidet', channexId: 'dced3634-738b-4c97-ba87-97b0c54c788e', type: null },
    { name: 'blowDryer', channexId: '36a4bcae-e011-4552-9088-7ebb9905ead1', type: null },
    { name: 'clothesDryer', channexId: '68189e53-293b-4451-b5ce-289de9dffd78', type: null },
    { name: 'essentials', channexId: '', type: null },
    { name: 'ironAndBoard', channexId: '734d5dfe-808e-43ef-82bd-54e7899da670', type: null },
    { name: 'shower', channexId: '93d62abc-cafb-4976-9ee0-b825b826fe91', type: null },
    { name: 'towelSet', channexId: 'bb81debf-dbe5-43ab-912d-33e20c09e856', type: null },
    { name: 'tub', channexId: '2b85eb67-c28a-45a9-a7d6-147f0e2391db', type: null },
    { name: 'washbasin', channexId: '', type: null },
    { name: 'washingMachine', channexId: 'e6e819a8-004e-498e-a578-c400a7171702', type: null },
  ],
  [CATEGORIES.COOKING]: [
    { name: 'blender', channexId: '', type: null },
    { name: 'childsHighChair', channexId: '22fc45ad-d19f-403a-93d0-4bc8d376c72a', type: null },
    { name: 'coffeeMachine', channexId: '25b7cd4a-ce28-4806-a198-8d00e55b3ef8', type: null },
    { name: 'cookingUtensils', channexId: '95999f89-538b-487c-b483-bcb4512f7d89', type: null },
    { name: 'dishWasher', channexId: '3efbafc4-8452-4550-a09e-fe11158323e3', type: null },
    { name: 'grill', channexId: '', type: null },
    { name: 'kitchenette', channexId: 'ee13f1e7-3cd6-43a1-91de-d94bad4761fe', type: null },
    { name: 'kitchenStove', channexId: '', type: null },
    { name: 'mealPlanAllInclusive', channexId: '', type: null },
    { name: 'mealPlanFullBoard', channexId: '', type: null },
    { name: 'mealPlanHalfBoard', channexId: '', type: null },
    { name: 'microwave', channexId: 'a78e66d0-627e-4137-b23a-0c5ffcb4bc00', type: null },
    { name: 'oven', channexId: 'dd69d2c1-4db1-47f1-8972-1ada843cf71f', type: null },
    { name: 'refrigerator', channexId: 'ea4cb7eb-44b0-439f-94ff-ddf23ae201c0', type: null },
    { name: 'riceSteamer', channexId: '', type: null },
    { name: 'spices', channexId: '', type: null },
    { name: 'toaster', channexId: '229ee913-a5a4-4a43-a317-18c28943c632', type: null },
    { name: 'waterCooler', channexId: '', type: null },
    { name: 'waterPurifier', channexId: '', type: null },
  ],
  [CATEGORIES.HEATING]: [
    { name: 'airConditioning', channexId: '9f5726e2-f979-4b6b-a69e-cbca387bc7ea', type: null },
    { name: 'ceilingFans', channexId: '', type: null },
    { name: 'centralHeating', channexId: '85dd90ff-d582-45a2-b6f9-b86155709deb', type: null },
    { name: 'electricHeating', channexId: '' },
    { name: 'fireplace', channexId: 'feffe2ff-67eb-4162-bcd8-01907c5500c6', type: null },
    { name: 'floorHeating', channexId: '' },
    { name: 'generalHeating', channexId: '85dd90ff-d582-45a2-b6f9-b86155709deb', type: null },
    { name: 'woodTiledStove', channexId: '', type: null },
  ],
  [CATEGORIES.MULTIMEDIA]: [
    { name: 'computer', channexId: '57e1258a-811a-4e4f-abf4-8865fb7c1c2c', type: null },
    { name: 'dvdPlayer', channexId: 'f051a21f-3502-42fe-8b3e-4cbbe3d4284f', type: null },
    { name: 'fax', channexId: '5d0f6cd3-05a5-446e-9d29-a10a6767aeb9', type: null },
    { name: 'internetBroadband', channexId: '5e359056-5a69-4876-9aef-7a961db18d79', type: null },
    { name: 'internetDialUp', channexId: '', type: null },
    { name: 'internetWireless', channexId: '6556b81d-62e2-454b-bdb7-b9b11f6bf57c', type: null },
    { name: 'piano', channexId: '', type: null },
    { name: 'stereoSystem', channexId: 'd7a28169-c126-4c47-81c7-31929cb9200e', type: null },
    { name: 'telephone', channexId: '3a5ef7dd-2915-4be5-b4b0-e13d15574321', type: null },
    { name: 'tvAntenna', channexId: '', type: null },
    { name: 'tvCable', channexId: '5df87db0-20dd-4b61-aa5d-fc747f1fd131', type: null },
    { name: 'tvSatellite', channexId: '35083174-001d-4994-a668-c09e0e4936e1', type: null },
  ],
  [CATEGORIES.OTHER]: [
    { name: 'vacuumCleaner', channexId: '', type: null },
  ],
  [CATEGORIES.OUTSIDE]: [
    { name: 'bbqCharcoalGrill', channexId: '2b9c558b-929c-46cc-9fc8-f7ce00fadd74', type: null },
    { name: 'bbqElectric', channexId: '', type: null },
    { name: 'bbqGas', channexId: '', type: null },
    { name: 'beachChairs', channexId: '', type: null },
    { name: 'bicycles', channexId: '', type: null },
    { name: 'boat', channexId: '', type: null },
    { name: 'canoeKayak', channexId: '', type: null },
    { name: 'gatedCommunity', channexId: '', type: null },
    { name: 'golfCart', channexId: '', type: null },
    { name: 'golfClubs', channexId: '', type: null },
    { name: 'motorboat', channexId: '', type: null },
    { name: 'privateGarden', channexId: '', type: null },
    { name: 'privatePlayground', channexId: '', type: null },
    { name: 'privatePorch', channexId: '', type: null },
    { name: 'privateTennisCourt', channexId: '', type: null },
    { name: 'sailboat', channexId: '', type: null },
    { name: 'sharedGarden', channexId: '', type: null },
    { name: 'sharedPlayground', channexId: '', type: null },
    { name: 'sharedPorch', channexId: '', type: null },
    { name: 'sharedTennisCourt', channexId: '', type: null },
  ],
  [CATEGORIES.PARKING]: [
    { name: 'garage', channexId: '', type: null },
    { name: 'parking', channexId: '', type: null },
    { name: 'parkingLot', channexId: '', type: null },
    { name: 'parkingOnStreet', channexId: '', type: null },
    { name: 'parkingOptionIncluded', channexId: '', type: null },
    { name: 'parkingOptionOptional', channexId: '', type: null },
    { name: 'parkingRoofedCarPort', channexId: '', type: null },
  ],
  [CATEGORIES.POLICIES]: [
    { name: 'acceptCreditCard', channexId: '', type: null },
    { name: 'accessible247', channexId: '', type: null },
    { name: 'breakfastIncluded', channexId: '', type: null },
    { name: 'childrenWelcome', channexId: '', type: null },
    { name: 'housekeeperIncluded', channexId: '', type: null },
    { name: 'housekeeperOptional', channexId: '', type: null },
    { name: 'laundryServiceIncluded', channexId: '', type: null },
    { name: 'laundryServiceOptional', channexId: '', type: null },
    { name: 'lowAllergenEnvironment', channexId: '', type: null },
    { name: 'petsAllowed', channexId: '', type: null },
    { name: 'petsAllowedOnlyAfterArrangement', channexId: '', type: null },
    { name: 'petsNotAllowed', channexId: '', type: null },
    { name: 'smokingAllowed', channexId: '', type: null },
    { name: 'smokingNotAllowed', channexId: '', type: null },
  ],
  [CATEGORIES.SAFETY]: [
    { name: 'buzzer', channexId: 'de2300fd-b800-428d-8ca4-82413d0c1e0b', type: null },
    { name: 'carbonMonoxideDetector', channexId: 'cbcc34e6-e55e-4490-a8e3-366d241a622d', type: null },
    { name: 'doorman', channexId: '', type: null },
    { name: 'fireExtinguisher', channexId: '553eb001-7395-4b20-82fa-912ede48fd81', type: null },
    { name: 'firstAidKit', channexId: '', type: null },
    { name: 'safe', channexId: '6e174877-c6e7-4ee7-a7af-abaaf07d72be', type: null },
    { name: 'safetyCard', channexId: '', type: null },
    { name: 'securitySystem', channexId: '', type: null },
    { name: 'smokeDetector', channexId: 'f611ff99-75d8-4f47-8533-9c120f6af02a', type: null },
  ],
  [CATEGORIES.SLEEPING]: [
    { name: 'bedLinen', channexId: '', type: null },
  ],
  [CATEGORIES.SPA]: [
    { name: 'foosball', channexId: '', type: null },
    { name: 'jacuzziIndoor', channexId: '', type: null },
    { name: 'jacuzziOutdoor', channexId: '', type: null },
    { name: 'pingPongTable', channexId: '', type: null },
    { name: 'poolTable', channexId: '', type: null },
    { name: 'privateDrySauna', channexId: '', type: null },
    { name: 'privateFitnessRoom', channexId: '', type: null },
    { name: 'privateHeatedSpaIndoorSwimmingPool', channexId: '', type: null },
    { name: 'privateHeatedSpaOutdoorSwimmingPool', channexId: '', type: null },
    { name: 'privateSteamSauna', channexId: '', type: null },
    { name: 'privateUnheatedSpaIndoorSwimmingPool', channexId: '', type: null },
    { name: 'privateUnheatedSpaOutdoorSwimmingPool', channexId: '', type: null },
    { name: 'sharedDrySauna', channexId: '', type: null },
    { name: 'sharedFitnessRoom', channexId: '', type: null },
    { name: 'sharedHeatedSpaIndoorSwimmingPool', channexId: '', type: null },
    { name: 'sharedHeatedSpaOutdoorSwimmingPool', channexId: '', type: null },
    { name: 'sharedSteamSauna', channexId: '', type: null },
    { name: 'sharedUnheatedSpaIndoorSwimmingPool', channexId: '', type: null },
    { name: 'sharedUnheatedSpaOutdoorSwimmingPool', channexId: '', type: null },
    { name: 'spaSwimmingPool', channexId: '', type: null },
  ],
  [CATEGORIES.VIEW]: [
    { name: 'innerCourtyardView', channexId: 'd55f1956-d789-4808-b0fa-adeeefe018fd', type: null },
    { name: 'gardenView', channexId: '8111bbfc-1894-45bd-bd90-bf5bc9b0b464', type: null },
    { name: 'cityView', channexId: '65b3dc4b-2aac-4d42-b58e-1086b858919d', type: null },
    { name: 'lakeView', channexId: 'd1aa2806-0228-4ed0-b482-1da9d8c9b5c2', type: null },
    { name: 'landmarkView', channexId: '15ed9ede-0c7f-4999-9041-d34ee776b8c5', type: null },
    { name: 'mountainView', channexId: '217a3ec9-9950-4063-9252-af2df78f36d0', type: null },
    { name: 'poolView', channexId: 'be8d5cde-f04a-415d-9183-13f5373c40bb', type: null },
    { name: 'quietStreetView', channexId: 'abe5192f-3d79-4c59-84de-9e6909c2e1db', type: null },
    { name: 'riverView', channexId: '36217e86-01c2-424c-8d81-b7573cf192c0', type: null },
    { name: 'seaView', channexId: 'e1d990b0-683c-4d1f-9151-c46c21aa6801', type: null },
  ],
}

exports.seed = (knex) => seed(knex, TABLE_NAME, Object.entries(DICTIONARY_AMENITIES)
  .map(([category, entries]) => entries.map(({ name, channexId, icon }) => ({
    category, name, channex_id: channexId, icon: icon || name,
  }))).flat())
