const { seed } = require('../../src/services/seeder')
const { TABLE_NAME } = require('../../src/models/v1/dict-fees/constants')

exports.seed = (knex) => seed(knex, TABLE_NAME, [
  { name: 'cleaningFee' },
  { name: 'miscCharges' },
  { name: 'damageProtectionInsurance' },
  { name: 'managementFee' },
  { name: 'serviceFee' },
  { name: 'additionalBed' },
  { name: 'airConditioning' },
  { name: 'propertyAssociation' },
  { name: 'babyBed' },
  { name: 'class' },
  { name: 'pool' },
  { name: 'poolHeating' },
  { name: 'concierge' },
  { name: 'electricity' },
  { name: 'equipment' },
  { name: 'food' },
  { name: 'gardening' },
  { name: 'gas' },
  { name: 'heating' },
  { name: 'highChair' },
  { name: 'hotTub' },
  { name: 'travelInsurance' },
  { name: 'internet' },
  { name: 'labor' },
  { name: 'laundry' },
  { name: 'linens' },
  { name: 'linensBath' },
  { name: 'linensBed' },
  { name: 'oil' },
  { name: 'onSitePaymentMethod' },
  { name: 'phone' },
  { name: 'parking' },
  { name: 'rent' },
  { name: 'resort' },
  { name: 'spa' },
  { name: 'toiletries' },
  { name: 'tour' },
  { name: 'transportation' },
  { name: 'utensilsCleaning' },
  { name: 'foodUtensils' },
  { name: 'vehicle' },
  { name: 'water' },
  { name: 'waterCraft' },
  { name: 'waterCraftMooring' },
  { name: 'drinkingWater' },
  { name: 'wood' },
])
