const { LIMITS } = require('../models/v1/limits/constants')
const { PACKAGES } = require('../models/v1/packages/constants')

module.exports = {
  [PACKAGES.BASIC]: { },

  [PACKAGES.PROFESSIONAL]: {
    [LIMITS.APP_STORAGE_QUOTA]: 1073741824, // 1 GB
    [LIMITS.APP_TEAM_SIZE_LIMIT]: 10,
    [LIMITS.APP_OWNERS_ENABLED]: 1,
    [LIMITS.APP_DOCUMENTS_ENABLED]: 1,
    [LIMITS.APP_DOCUMENTS_INVOICES_ENABLED]: 1,
    // [LIMITS.APP_WEBSITE_BUILDER_ENABLED]: 1,
    [LIMITS.APP_SERVICES_REMINDERS_SIZE_LIMIT]: 20,
    [LIMITS.APP_FEES_SIZE_LIMIT]: 10,
    [LIMITS.APP_TAXES_SIZE_LIMIT]: 10,
    [LIMITS.APP_RATE_SEASONS_SIZE_LIMIT]: 10,
    [LIMITS.APP_PROPERTIES_SIZE_LIMIT]: 50,
    [LIMITS.APP_PROPERTIES_UNIT_TYPES_SIZE_LIMIT]: 10,
    [LIMITS.APP_PROPERTIES_UNITS_SIZE_LIMIT]: 5,
    [LIMITS.APP_PROPERTIES_UNIT_TYPES_SEASONS_SIZE_LIMIT]: 5,
  },

  [PACKAGES.ENTERPRISE]: {
    [LIMITS.APP_STORAGE_QUOTA]: 5368709120, // 5 GB
    [LIMITS.APP_TEAM_SIZE_LIMIT]: 50,
    [LIMITS.APP_OWNERS_ENABLED]: 1,
    [LIMITS.APP_DOCUMENTS_ENABLED]: 1,
    [LIMITS.APP_DOCUMENTS_INVOICES_ENABLED]: 1,
    // [LIMITS.APP_WEBSITE_BUILDER_ENABLED]: 1,
    [LIMITS.APP_SERVICES_REMINDERS_SIZE_LIMIT]: 50,
    [LIMITS.APP_FEES_SIZE_LIMIT]: 50,
    [LIMITS.APP_TAXES_SIZE_LIMIT]: 50,
    [LIMITS.APP_RATE_SEASONS_SIZE_LIMIT]: 100,
    [LIMITS.APP_PROPERTIES_SIZE_LIMIT]: 150,
    [LIMITS.APP_PROPERTIES_UNIT_TYPES_SIZE_LIMIT]: 50,
    [LIMITS.APP_PROPERTIES_UNITS_SIZE_LIMIT]: 15,
    [LIMITS.APP_PROPERTIES_UNIT_TYPES_SEASONS_SIZE_LIMIT]: 10,
  },
}
