const express = require('express')

const checkSubscription = require('../../../../middlewares/subscription')
const phoneVerification = require('../../../../middlewares/phoneVerification')
const { jwtUserGuard } = require('../../../../middlewares/guards')

const app = express()

app.use('/auth', require('./auth'))
app.use('/billings', jwtUserGuard, require('./billings'))
app.use('/me', jwtUserGuard, require('./me'))
app.get('/config', jwtUserGuard, require('./config'))
app.get('/limits', jwtUserGuard, require('./limits'))
app.use('/account', jwtUserGuard, require('./account'))
app.use('/dictionaries', jwtUserGuard, require('./dictionaries'))
app.use('/bookings', jwtUserGuard, phoneVerification, checkSubscription, require('./bookings'))
app.use('/channel-managers', jwtUserGuard, phoneVerification, checkSubscription, require('./channel-managers'))
app.use('/companies', jwtUserGuard, phoneVerification, checkSubscription, require('./companies'))
app.use('/documents', jwtUserGuard, phoneVerification, checkSubscription, require('./documents'))
app.use('/fees', jwtUserGuard, phoneVerification, checkSubscription, require('./fees'))
app.use('/taxes', jwtUserGuard, phoneVerification, checkSubscription, require('./taxes'))
app.use('/guests', jwtUserGuard, phoneVerification, checkSubscription, require('./guests'))
app.use('/integrations', jwtUserGuard, phoneVerification, checkSubscription, require('./integrations'))
app.use('/languages', jwtUserGuard, phoneVerification, checkSubscription, require('./languages'))
app.use('/locations', jwtUserGuard, phoneVerification, checkSubscription, require('./locations'))
app.use('/owners', jwtUserGuard, phoneVerification, checkSubscription, require('./owners'))
app.use('/permissions', jwtUserGuard, phoneVerification, checkSubscription, require('./permissions'))
app.use('/properties', jwtUserGuard, phoneVerification, checkSubscription, require('./properties'))
app.use('/rate-seasons', jwtUserGuard, phoneVerification, checkSubscription, require('./rate-seasons'))
app.use('/sales-channels', jwtUserGuard, phoneVerification, checkSubscription, require('./sales-channels'))
app.use('/service-providers', jwtUserGuard, phoneVerification, checkSubscription, require('./service-providers'))
app.use('/customer-contacts', jwtUserGuard, phoneVerification, checkSubscription, require('./customer-contacts'))
app.use('/services', jwtUserGuard, phoneVerification, checkSubscription, require('./services'))
app.use('/statistics', jwtUserGuard, phoneVerification, checkSubscription, require('./statistics'))
app.use('/storage', jwtUserGuard, phoneVerification, checkSubscription, require('./storage'))
app.use('/users', jwtUserGuard, phoneVerification, checkSubscription, require('./users'))
app.use('/websites', jwtUserGuard, phoneVerification, checkSubscription, require('./websites'))

module.exports = app
