components:
  schemas:
    GuestCreateRequest:
      allOf:
        - type: object
          required:
            - phoneNumber
            - firstName
            - lastName
        - $ref: '#/components/schemas/GuestUpdateRequest'

    GuestUpdateRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          example: "johndoe@domain.com"
        phoneNumber:
          type: string
          example: "+41777777777"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        title:
          type: string
          enum:
            - mr
            - ms
            - mrs
            - miss
            - mx
          example: "mr"
        gender:
          type: string
          enum:
            - m
            - f
            - other
          example: "m"
        birthDate:
          type: string
          format: date
          example: "2021-02-11"
        birthPlace:
          type: string
          minLength: 2
          maxLength: 191
          example: "Warsaw"
        citizenship:
          type: string
          minLength: 2
          maxLength: 2
          example: "PL"
        address:
          type: string
          minLength: 2
          maxLength: 191
          example: "Bahnhofstrasse 100 c/o Schmit"
        city:
          type: string
          minLength: 2
          maxLength: 191
          example: "Zurich"
        zip:
          type: string
          maxLength: 40
          example: "NW1 4DS"
        region:
          type: string
          minLength: 2
          maxLength: 191
          example: "ZH"
        countryCode:
          type: string
          minLength: 2
          maxLength: 2
          example: "CH"
        documentType:
          type: string
          enum:
            - idCard
            - passport
            - drivingLicense
          example: "passport"
        documentNumber:
          type: string
          example: "ABCVFG24W"
        documentIssuedDate:
          type: string
          format: date
          example: "2012-02-15"
        documentExpiryDate:
          type: string
          format: date
          example: "2027-02-19"
        parlance:
          type: array
          items:
            type: string
            minLength: 2
            maxLength: 2
            example: "en"
        labels:
          type: array
          items:
            type: object
            required:
              - name
            properties:
              name:
                type: string
                example: "vip"
        notes:
          type: string
          example: "VIP Guest"

    GuestCollectionResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              email:
                type: string
                format: email
                example: "johndoe@domain.com"
              phoneNumber:
                type: string
                example: "+41777777777"
              gender:
                type: string
                enum:
                  - m
                  - f
                  - other
                example: "m"
              title:
                type: string
                enum:
                  - mr
                  - mrs
                  - ms
                  - miss
                  - mx
                example: "mr"
              firstName:
                type: string
                example: "John"
              lastName:
                type: string
                example: "Doe"
              labels:
                type: array
                items:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                      example: "VIP"

    GuestItemResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          properties:
            email:
              type: string
            phoneNumber:
              type: string
              example: "+41777777777"
            gender:
              type: string
              enum:
                - m
                - f
                - other
              example: "m"
            title:
              type: string
              enum:
                - mr
                - mrs
                - ms
                - miss
                - mx
              example: "mr"
            firstName:
              type: string
              example: "John"
            lastName:
              type: string
              example: "Doe"
            citizenship:
              type: string
              example: "PL"
            address:
              type: string
              example: "Bahnhofstrasse 100 c/o Schmit"
            city:
              type: string
              example: "Zurich"
            zip:
              type: string
              example: "NW1 4DS"
            region:
              type: string
              example: "ZH"
            countryCode:
              type: string
              example: "CH"
            documentType:
              type: string
              enum:
                - passport
                - drivingLicense
                - idCard
              example: "passport"
            documentNumber:
              type: string
              example: "ABCVFG24W"
            documentIssuedDate:
              type: string
              format: date
              example: "2012-02-15"
            documentExpiryDate:
              type: string
              format: date
              example: "2024-02-15"
            birthDate:
              type: string
              format: date
              example: "1995-05-05"
            birthPlace:
              type: string
              example: "Warsaw"
            labels:
              type: array
              items:
                type: object
                required:
                  - name
                properties:
                  name:
                    type: string
                    example: "VIP"
            parlance:
              type: array
              items:
                type: string
                example: "en"
            notes:
              type: string
              example: "VIP guest"
