const { serialize } = require('../../../services/serializers')

exports.PERMITED_ITEM_PARAMS = [
  'id',
  'propertyUnitTypeId',
  'rateId',
  'name',
  'currency',
  'cancellationPolicy',
  'pricesNightly',
  'discountEnabled',
  'discountType',
  'discountWeekly',
  'discountMonthly',
  'discountCustomEnabled',
  'discountCustom',
  'discountCustomPeriod',
  'minStayDays',
  'minStayWeekdayEnabled',
  'minStayWeekdayMo',
  'minStayWeekdayTu',
  'minStayWeekdayWe',
  'minStayWeekdayTh',
  'minStayWeekdayFr',
  'minStayWeekdaySa',
  'minStayWeekdaySu',
  'occupancyEnabled',
  'occupancyStartsAfterPerson',
  'occupancyExtraCharge',
  'shortStayEnabled',
  'shortStayDays',
  'shortStayExtraCharge',
  'selfServiceRestrictionsEnabled',
  'selfServiceCheckinMo',
  'selfServiceCheckinTu',
  'selfServiceCheckinWe',
  'selfServiceCheckinTh',
  'selfServiceCheckinFr',
  'selfServiceCheckinSa',
  'selfServiceCheckinSu',
  'selfServiceCheckoutMo',
  'selfServiceCheckoutTu',
  'selfServiceCheckoutWe',
  'selfServiceCheckoutTh',
  'selfServiceCheckoutFr',
  'selfServiceCheckoutSa',
  'selfServiceCheckoutSu',
  'taxEnabled',
  'taxIncluded',
  'taxPercentage',
  'notesEnabled',
  'notes',
  'createdAt',
  'updatedAt',
]

exports.serialize = serialize
